site_name: Opossum Search Documentation
site_description: Documentation for the Opossum Search system
site_author: bebo

# Repository
# repo_name: opossum-search
# repo_url: https://github.com/yourusername/opossum-search

# Theme configuration
theme:
  name: readthedocs
  # favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.details
  - toc:
      permalink: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - First Steps: technical/getting-started.md
      - System Overview: technical/system-architecture-overview.md
      - API Reference: api/getting-started.md
      - Developer Quickstart: technical/devops-guide.md
  
  - Core Components:
      - Architecture:
          - System Architecture: technical/system-architecture-overview.md
          - GraphQL API: technical/graphql-api.md
          - Security Model: technical/security-model.md
      - Model Integration:
          - Architecture: model-integration/architecture.md
          - Backend Selection: model-integration/backend-selection.md
          - Capability Matrix: model-integration/capability-matrix.md
          - Provider Integration: model-integration/providers.md
          - Configuration: model-integration/configuration.md
          - Hybrid Selection: technical/hybrid-model-selection.md
      - Service Availability:
          - Context and Scope: service-availability/context-and-scope.md
          - Quality Requirements: service-availability/quality-requirements.md
          - Architecture Constraints: service-availability/architecture-constraints.md
          - Availability Monitoring: service-availability/availability-monitoring.md
          - Error Handling: service-availability/service-outage.md
      - Resilience Patterns:
          - Core Strategies: technical/resilience-patterns.md
          - Error Handling: technical/error-handling-resilience.md
          - Rate Limiting: service-availability/rate-limiting-throttling.md
          - Logging and Alerts: service-availability/log-alerts.md
          - Testing and Validation: service-availability/testing-validation.md
  
  - Features:
      - Conversation:
          - Topic Detection: conversation/topic-detection.md
          - Conversation Flow: conversation/conversation-flow.md
          - Response Generation: conversation/response-generation.md
          - NLP Components: conversation/nlp-components.md
          - Markov Generation: conversation/markov-generation.md
      - Image Processing:
          - Overview: image-processing/overview.md
          - Effects and Filters: image-processing/effects.md
          - SVG Generation: image-processing/svg-generation.md
          - Performance Optimization: image-processing/optimization.md
          - Caching Strategy: image-processing/caching.md
      - Visualizations & Fun:
          - Service Visualizations: features/service-vizualizations.md
          - National Opossum Day: features/national-day.md
          - Easter Eggs: features/easter-eggs.md
          - Special Events: features/special-events.md
          - Background Stories: features/background-stories.md
  
  - Technical Reference:
      - Infrastructure:
          - Redis Caching: technical/redis-caching-architecture.md
          - Image Pipeline: technical/image-processing-pipeline.md
          - OpenTelemetry: technical/opentelemetry-integration.md
          - SVG Markup: technical/svg-markup.md
          - Bot User Simulation: technical/bot-user-simulation.md
          - Optimization Strategies: infrastructure/optimization-strategies.md
      - API Documentation:
          - Routes: api/routes.md
          - Request/Response: api/request-response.md
          - OAuth Configuration: api/oauth-configuration.md
          - Error Codes: api/error-codes.md
          - Rate Limits: api/rate-limits.md
          - Webhook Integration: api/webhooks.md
          - Health Endpoints: api/health-endpoints.md
          - Compliance: api/compliance.md
  
  - About:
      - Project History: about/history.md
      - Team: about/team.md
      - Roadmap: about/roadmap.md

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mermaid2
