site_name: Opossum Search Documentation
site_description: Documentation for the Opossum Search system
site_author: bebo

# Repository
# repo_name: opossum-search
# repo_url: https://github.com/yourusername/opossum-search

# Theme configuration
theme:
  name: readthedocs
  # favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

# Navigation structure
nav:
  - Home: index.md
  - Service Availability:
    - Context and Scope: service-availability/context-and-scope.md
    - Quality Requirements: service-availability/quality-requirements.md
    - Architecture Constraints: service-availability/architecture-constraints.md
    - Availability Monitoring: service-availability/availability-monitoring.md
    - Error Handling: service-availability/service-outage.md
    - Rate Limiting: service-availability/rate-limiting-throttling.md
    - Logging and Alerts: service-availability/log-alerts.md
    - Fallback Mechanisms: service-availability/fallback-mechanisms.md
    - Testing and Validation: service-availability/testing-validation.md
    - Diagrams: service-availability/processing-diagrams.md

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mermaid2