site_name: Opossum Search Documentation
site_description: Documentation for the Opossum Search system
site_author: bebo

# Repository
# repo_name: Opossum
# repo_url: https://github.com/bilalobe/Opossum

# Theme configuration - upgraded to Material theme
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: material/magnify
    favicon: material/magnify

# Extensions - enhanced with additional markdown extensions
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - toc:
      permalink: true

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - First Steps: technical/getting-started.md
      - System Overview: technical/system-architecture-overview.md
      - API Reference: api/getting-started.md
      - Developer Quickstart: technical/devops-guide.md
  
  - Core Components:
      - Architecture:
          - System Architecture: technical/system-architecture-overview.md
          - Model Context Protocol (MCP): technical/mcp-architecture.md
          - GraphQL API: technical/graphql-api.md
          - Security Model: technical/security-model.md
          - Prompt Management: technical/prompt-management.md
      - Model Integration:
          - Architecture: model-integration/architecture.md
          - Backend Selection: model-integration/backend-selection.md
          - Capability Matrix: model-integration/capability-matrix.md
          - Provider Integration: model-integration/providers.md
          - Configuration: model-integration/configuration.md
          - Hybrid Selection: technical/hybrid-model-selection.md
          - Prompt Management: technical/prompt-management.md
          # New DSPy integration pages
          - DSPy Integration: model-integration/dspy-integration.md
          - DSPy Technical Implementation: model-integration/dspy-technical.md
          - DSPy Usage Examples: model-integration/dspy-examples.md
          - DSPy Metrics & Performance: model-integration/dspy-metrics.md
      - Service Availability:
          - Context and Scope: service-availability/context-and-scope.md
          - Quality Requirements: service-availability/quality-requirements.md
          - Architecture Constraints: service-availability/architecture-constraints.md
          - Availability Monitoring: service-availability/availability-monitoring.md
          - Error Handling: service-availability/service-outage.md
      - Resilience Patterns:
          - Core Strategies: technical/resilience-patterns.md
          - Error Handling: technical/error-handling-resilience.md
          - Rate Limiting: service-availability/rate-limiting-throttling.md
          - Logging and Alerts: service-availability/log-alerts.md
          - Testing and Validation: service-availability/testing-validation.md
  
  - Features:
      - Conversation:
          - Topic Detection: conversation/topic-detection.md
          - Conversation Flow: conversation/conversation-flow.md
          - Response Generation: conversation/response-generation.md
          - NLP Components: conversation/nlp-components.md
          - Markov Generation: conversation/markov-generation.md
      - Image Processing:
          - Overview: image-processing/overview.md
          - Effects and Filters: image-processing/effects.md
          - SVG Generation: image-processing/svg-generation.md
          - Performance Optimization: image-processing/optimization.md
          - Caching Strategy: image-processing/caching.md
      - Visualizations & Fun:
          - Service Visualizations: features/service-vizualizations.md
          - National Opossum Day: features/national-day.md
          - Opossum Xenzia: features/opossum-xenzia.md
          - Easter Eggs: features/easter-eggs.md
          - Special Events: features/special-events.md
          - Background Stories: features/background-stories.md
  
  - Technical Reference:
      - Infrastructure:
          - Redis Caching: technical/redis-caching-architecture.md
          - Image Pipeline: technical/image-processing-pipeline.md
          - OpenTelemetry: technical/opentelemetry-integration.md
          - SVG Markup: technical/svg-markup.md
          - Bot User Simulation: technical/bot-user-simulation.md
          - Optimization Strategies: infrastructure/optimization-strategies.md
          - Pipeline Optimization: infrastructure/pipeline-optimization.md
          - Constraint Mapping: infrastructure/constraint-mapping.md
      - API Documentation:
          - Routes: api/routes.md
          - Request/Response: api/request-response.md
          - OAuth Configuration: api/oauth-configuration.md
          - Error Codes: api/error-codes.md
          - Rate Limits: api/rate-limits.md
          - Webhook Integration: api/webhooks.md
          - Health Endpoints: api/health-endpoints.md
          - Compliance: api/compliance.md
      # New DSPy Tutorials section
      - DSPy Tutorials:
          - Getting Started with DSPy: tutorials/dspy/getting-started.md
          - Optimizing Prompts: tutorials/dspy/optimizing-prompts.md
          - Building Pipelines: tutorials/dspy/building-pipelines.md
          - Advanced Reasoning: tutorials/dspy/advanced-reasoning.md
  
  - About:
      - Project History: about/history.md
      - The Opossumial Way: about/opossumial-way.md
      - Team: about/team.md
      - Roadmap & Vision: about/roadmap-vision.md

# Enhanced plugins
plugins:
  - search
  - minify:
      minify_html: true
  - mermaid2
  # New plugins inspired by DSPy
  # Optional: Add if you want to include Jupyter notebooks
  # - mkdocs-jupyter:
  #     ignore_h1_titles: True
  # Optional: Add if you want auto-generated API docs
  - mkdocstrings:
      handlers:
          python:
              options:
                  docstring_style: google
                  show_source: true

# Extra CSS for customizations
extra_css:
  - stylesheets/extra.css

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bilalobe/Opossum
